### ISSUE TITLE
Details about Shortcuts

### ISSUE THREAD

**Issue by rfoel** [rfviolato/work-commute#2]
Loved the idea, loved the project, I will probably give it a shot on my own. I have a quick question tho. How did you set up the Shortcuts? Can you give more details about it? I want to know how the geofencing works in this case.

**Comment by rfviolato** [comment]
Hello there! Thanks :)
It's [built-in functionality](https://support.apple.com/en-gb/guide/shortcuts/apd690170742/ios) that is available on the iOS version 13:
![IMG_3A6BFE71D613-1](https://user-images.githubusercontent.com/5693916/74836683-28652e80-5320-11ea-8fc6-afc73c5ea0c4.jpeg)

You basically choose "enter" or "leave" location as the trigger and then you run any shortcuts-like routine, including another shortcut.
The only flaw on this is that it is not yet run automatically, so what it just display a top-notification asking to run the automation, but there are apps out there to bypass that (but I haven't tried those).

**Comment by rfoel** [comment]
Show de bola! Did you have any idempotency problems with your requests? It may trigger the automation more than once depending on the GPS signal.

**Comment by rfviolato** [comment]
I haven't experienced that, I think iOS takes care of this somehow (GPS signal issue). The only thing that I have experienced is that the train I take to work passes in front of the office, so I get 2x the "Do you want to run the work arrived automation?" notification twice 😅 , once on the train arrival and once when actually arriving at the office. That happens because the smallest radius that you can set for the trigger is not enough in this situation, I would need an even smaller radius.

About the requests themselves, because of the nature of them not being fully automatically triggered, I did not get any issues.

**Comment by rfoel** [comment]
Got it. I love to see these kind of projects. Keep improving!
